groups:
  - name: group_basic
    rules:
      - alert: HighCPUUsage
        expr: avg_over_time(cpu_usage[5m])>80
        for: 0s  # pending period
        labels:
          severity: critical
        annotations:
          summary: "CPU usage excedded 80%"
          description: "CPU usage has been above 80% for the last 5 minutes."
